### ISSUE TITLE
does not work - TO error

### ISSUE THREAD

**Issue by jayjayuk** [bertmelis/esp32DHT#1]
connected correctly and use the correct pin as in sketch, also tried pin 26 and pin 18, always error=TO.

i have tried other library dht library and i can get the results for this sensor so it has to be library related.

the example included does compile but always get error=TO . other examples i find on github page must be for an older version of the library where functions have been removed... so does not compile

**Comment by bertmelis** [comment]
I'll look into it.

**Comment by bertmelis** [comment]
Tested and merged the referenced PR. All is working now.
(I tested with a lolin32 on a breadboard, no external pullup, DHT powered from 3V3)

Feel free to reopen if it still doesn't work on your side.
