### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by kbickham** [bertmelis/esp32DHT#3]
I'm a little unsure about the syntax/arguments for the rmt channels here. Dig the philosophy behind what you're doing as I'm used to sampling these on avr. The esp32 technical manual is not too descriptive, I'm instantiating 3 instances:

<details>
<summary>Details</summary>

'#include <Arduino.h>
#include <Ticker.h>
#include <esp32DHT.h>

Ticker tick1,tick2,tick3;
DHT22 dht,dht2,dht3;
// DHT11 sensor;  // DHT11 also works!

void readDHT() {
  dht.read();
    dht2.read();
      dht3.read();
}

void setup()
{
  Serial.begin(74880);
  dht.setup(5,0);  // pin 23 is DATA, RMT channel defaults to channel 0 and 1
  dht.onData([](float humidity, float temperature){
    Serial.printf("Temp: %g°C\nHumid: %g%%\n", temperature,humidity);
    });
  dht.onError([](uint8_t error){
    Serial.printf("Sensor error: %s", sensor.getError());
    });
  tick1.attach(5, readDHT);

  dht2.setup(18,1);  // pin 23 is DATA, RMT channel defaults to channel 0 and 1
  dht2.onData([](float humidity, float temperature){
    Serial.printf("Temp: %g°C\nHumid: %g%%\n", temperature,humidity);
      });
  dht2.onError([](uint8_t error) {
    Serial.printf("Sensor error: %s", sensor.getError());
    });
  tick2.attach(18, readDHT);

  dht3.setup(19,2);  // pin 23 is DATA, RMT channel defaults to channel 0 and 1
  dht3.onData([](float humidity, float temperature){
    Serial.printf("Temp: %g°C\nHumid: %g%%\n", temperature,humidity);
    });
  dht3.onError([](uint8_t error) {
    Serial.printf("Sensor error: %s", sensor.getError());
    });
  tick3.attach(19, readDHT);
}
'

</details>

Errors from compiler

<details>
<summary>Details</summary>

':\Users\Lauren\Downloads\arduino-nightly\sketches\sensornet\sensornet.ino: In function 'void setup()':

sensornet:20:16: error: invalid conversion from 'int' to 'rmt_channel_t' [-fpermissive]

   dht.setup(5,0);  // pin 23 is DATA, RMT channel defaults to channel 0 and 1

                ^

In file included from C:\Users\Lauren\Downloads\arduino-nightly\sketches\libraries\esp32DHT-master\src/esp32DHT.h:27:0,

                 from C:\Users\Lauren\Downloads\arduino-nightly\sketches\sensornet\sensornet.ino:5:

C:\Users\Lauren\Downloads\arduino-nightly\sketches\libraries\esp32DHT-master\src/esp32DHT.hpp:47:8: note:   initializing argument 2 of 'void DHT::setup(uint8_t, rmt_channel_t)'

   void setup(uint8_t pin, rmt_channel_t channel = RMT_CHANNEL_0);  // setPin does complete setup of DHT lib

        ^

C:\Users\Lauren\Downloads\arduino-nightly\sketches\sensornet\sensornet.ino: In lambda function:

sensornet:25:39: error: 'sensor' was not declared in this scope

     Serial.printf("Sensor error: %s", sensor.getError());

                                       ^

C:\Users\Lauren\Downloads\arduino-nightly\sketches\sensornet\sensornet.ino: In function 'void setup()':

sensornet:29:18: error: invalid conversion from 'int' to 'rmt_channel_t' [-fpermissive]

   dht2.setup(18,1);  // pin 23 is DATA, RMT channel defaults to channel 0 and 1

                  ^

In file included from C:\Users\Lauren\Downloads\arduino-nightly\sketches\libraries\esp32DHT-master\src/esp32DHT.h:27:0,

                 from C:\Users\Lauren\Downloads\arduino-nightly\sketches\sensornet\sensornet.ino:5:

C:\Users\Lauren\Downloads\arduino-nightly\sketches\libraries\esp32DHT-master\src/esp32DHT.hpp:47:8: note:   initializing argument 2 of 'void DHT::setup(uint8_t, rmt_channel_t)'

   void setup(uint8_t pin, rmt_channel_t channel = RMT_CHANNEL_0);  // setPin does complete setup of DHT lib

        ^

C:\Users\Lauren\Downloads\arduino-nightly\sketches\sensornet\sensornet.ino: In lambda function:

sensornet:34:39: error: 'sensor' was not declared in this scope

     Serial.printf("Sensor error: %s", sensor.getError());

                                       ^

C:\Users\Lauren\Downloads\arduino-nightly\sketches\sensornet\sensornet.ino: In function 'void setup()':

sensornet:38:18: error: invalid conversion from 'int' to 'rmt_channel_t' [-fpermissive]

   dht3.setup(19,2);  // pin 23 is DATA, RMT channel defaults to channel 0 and 1

                  ^

In file included from C:\Users\Lauren\Downloads\arduino-nightly\sketches\libraries\esp32DHT-master\src/esp32DHT.h:27:0,

                 from C:\Users\Lauren\Downloads\arduino-nightly\sketches\sensornet\sensornet.ino:5:

C:\Users\Lauren\Downloads\arduino-nightly\sketches\libraries\esp32DHT-master\src/esp32DHT.hpp:47:8: note:   initializing argument 2 of 'void DHT::setup(uint8_t, rmt_channel_t)'

   void setup(uint8_t pin, rmt_channel_t channel = RMT_CHANNEL_0);  // setPin does complete setup of DHT lib

        ^

C:\Users\Lauren\Downloads\arduino-nightly\sketches\sensornet\sensornet.ino: In lambda function:

sensornet:43:39: error: 'sensor' was not declared in this scope

     Serial.printf("Sensor error: %s", sensor.getError());

                                       ^

Using library Ticker at version 1.1 in folder: C:\Users\Lauren\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.2\libraries\Ticker 
Using library esp32DHT-master at version 1.0.1 in folder: C:\Users\Lauren\Downloads\arduino-nightly\sketches\libraries\esp32DHT-master 
exit status 1
invalid conversion from 'int' to 'rmt_channel_t' [-fpermissive]
'

</details>

**Comment by bertmelis** [comment]
I must admit I never tested the code with. multiple sensors. RMT channel is a definition in ESP-IDF. Caveat is that you don't have overlapping memory areas for the different sensors (or other peripherals).

I'll look into the matter this evening (I'm on Warsaw timezone now).

**Comment by bertmelis** [comment]
RMT channel has to be passed as ` RMT_CHANNEL_0` or ` RMT_CHANNEL_2` ...

Example added in readme.
